#ifndef _PICO_MEMMAP_H
#define _PICO_MEMMAP_H

#define PICO_FLASH_BASE 0x10000000
#define PICO_FLASH_LENGTH 0x200000
#define PICO_FLASH_LIMIT (PICO_FLASH_BASE + PICO_FLASH_LENGTH)

#if PICO_USE_BLOCKED_RAM
#define PICO_RAM_BASE 0x21000000
#else
#define PICO_RAM_BASE 0x20000000
#endif
#define PICO_RAM_LENGTH 0x40000
#define PICO_RAM_LIMIT (PICO_RAM_BASE + PICO_RAM_LENGTH)

#define PICO_SCRATCH_X_BASE 0x20040000
#define PICO_SCRATCH_X_LENGTH 0x1000
#define PICO_SCRATCH_X_LIMIT (PICO_SCRATCH_X_BASE + PICO_SCRATCH_X_LENGTH)

#define PICO_SCRATCH_Y_BASE 0x20041000
#define PICO_SCRATCH_Y_LENGTH 0x1000
#define PICO_SCRATCH_Y_LIMIT (PICO_SCRATCH_Y_BASE + PICO_SCRATCH_Y_LENGTH)

#endif
