/*
 * Copyright (c) 2026 Raspberry Pi Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* Use <<EOF>> rather than yywrap() to handle end-of-file */
%option noyywrap

/* We don't use unput() */
%option nounput

/* We don't use input() */
%option noinput

/* Don't implement a default rule for us */
%option nodefault

/* Declare lexer states */
%x COMMENT

/* Literal insertions into lexer.cpp (near top) */
%{

#include <iostream>

#include "Diagnostic.h"
#include "parser.hpp"
#include "SourceManager.h"
#include "lexer.h"
#include "main.h"

//#define TRACE(msg) std::cout << "Lexed " << msg << std::endl;
#define TRACE(msg)

/* Current location */
static SourceLocation current_location;
/* Location of most recently-lexed symbol */
SourceLocation lexer_symbol_location;

/* Include resumption stack */
static std::vector<SourceLocation> resume_locations;

#define ADVANCE() \
    do { \
        lexer_symbol_location = current_location; \
        current_location.offset += static_cast<std::size_t>(yyleng); \
    } while (0)

/* Since we've used %define api.token.constructor, we need to redefine YY_DECL
 * so that rather than returning an integer token type, yylex() returns an
 * object of type yy::parser::symbol_type, as generated by the various
 * make_* factory functions.
 */
#define YY_DECL yy::parser::symbol_type yylex()

static YY_BUFFER_STATE my_scan_buffer(FileId id);

%}

/* pattern/action pairs */
%%

"/*" {
    /* Start discarding comments */
    ADVANCE();
    BEGIN(COMMENT);
}

<COMMENT>"*/" {
    /* End of comment */
    ADVANCE();
    BEGIN(INITIAL);
}

<COMMENT>\n {
    ADVANCE();
    g_source_manager.addLine(current_location);
}

<COMMENT><<EOF>> {
    throw DiagnosticError(current_location, "Unterminated comment");
}

<COMMENT>. {
    /* Discard comment */
    ADVANCE();
}

[ \t\r]+ {
    /* Skip whitespace */
    ADVANCE();
}

ENTRY {
    TRACE("ENTRY")
    ADVANCE();
    return yy::parser::make_ENTRY(lexer_symbol_location);
}

INCLUDE {
    TRACE("INCLUDE")
    ADVANCE();
    return yy::parser::make_INCLUDE(lexer_symbol_location);
}

MEMORY {
    TRACE("MEMORY")
    ADVANCE();
    return yy::parser::make_MEMORY(lexer_symbol_location);
}

SECTIONS {
    TRACE("SECTIONS")
    ADVANCE();
    return yy::parser::make_SECTIONS(lexer_symbol_location);
}

REGION_ALIAS {
    TRACE("REGION_ALIAS")
    ADVANCE();
    return yy::parser::make_REGION_ALIAS(lexer_symbol_location);
}

ASSERT {
    TRACE("ASSERT")
    ADVANCE();
    return yy::parser::make_ASSERT(lexer_symbol_location);
}

AT> {
    TRACE("AT_NAMED")
    ADVANCE();
    return yy::parser::make_AT_NAMED(lexer_symbol_location);
}

AT {
    TRACE("AT")
    ADVANCE();
    return yy::parser::make_AT(lexer_symbol_location);
}

EXCLUDE_FILE {
    TRACE("EXCLUDE_FILE")
    ADVANCE();
    return yy::parser::make_EXCLUDE_FILE(lexer_symbol_location);
}

KEEP {
    TRACE("KEEP")
    ADVANCE();
    return yy::parser::make_KEEP(lexer_symbol_location);
}

NOLOAD {
    TRACE("NOLOAD")
    ADVANCE();
    return yy::parser::make_NOLOAD(lexer_symbol_location);
}

PROVIDE_HIDDEN {
    TRACE("PROVIDE_HIDDEN")
    ADVANCE();
    return yy::parser::make_PROVIDE_HIDDEN(lexer_symbol_location);
}

PROVIDE {
    TRACE("PROVIDE")
    ADVANCE();
    return yy::parser::make_PROVIDE(lexer_symbol_location);
}

SORT_BY_ALIGNMENT {
    TRACE("SORT_BY_ALIGNMENT")
    ADVANCE();
    return yy::parser::make_SORT_BY_ALIGNMENT(lexer_symbol_location);
}

SORT(_BY_NAME)? {
    TRACE("SORT_BY_NAME")
    ADVANCE();
    return yy::parser::make_SORT_BY_NAME(lexer_symbol_location);
}

ALIGNOF {
    TRACE("ALIGNOF")
    ADVANCE();
    return yy::parser::make_ALIGNOF(lexer_symbol_location);
}

ALIGN {
    TRACE("ALIGN")
    ADVANCE();
    return yy::parser::make_ALIGN(lexer_symbol_location);
}

DEFINED {
    TRACE("DEFINED")
    ADVANCE();
    return yy::parser::make_DEFINED(lexer_symbol_location);
}

LENGTH {
    TRACE("LENGTH")
    ADVANCE();
    return yy::parser::make_LENGTH(lexer_symbol_location);
}

LOADADDR {
    TRACE("LOADADDR")
    ADVANCE();
    return yy::parser::make_LOADADDR(lexer_symbol_location);
}

MAX {
    TRACE("MAX")
    ADVANCE();
    return yy::parser::make_MAX(lexer_symbol_location);
}

ORIGIN {
    TRACE("ORIGIN")
    ADVANCE();
    return yy::parser::make_ORIGIN(lexer_symbol_location);
}

SIZEOF {
    TRACE("SIZEOF")
    ADVANCE();
    return yy::parser::make_SIZEOF(lexer_symbol_location);
}

"=" {
    TRACE("ASSIGN")
    ADVANCE();
    return yy::parser::make_ASSIGN(lexer_symbol_location);
}

"&" {
    TRACE("BITWISE_AND")
    ADVANCE();
    return yy::parser::make_BITWISE_AND(lexer_symbol_location);
}

"~" {
    TRACE("BITWISE_NOT")
    ADVANCE();
    return yy::parser::make_BITWISE_NOT(lexer_symbol_location);
}

":" {
    TRACE("COLON")
    ADVANCE();
    return yy::parser::make_COLON(lexer_symbol_location);
}

"," {
    TRACE("COMMA")
    ADVANCE();
    return yy::parser::make_COMMA(lexer_symbol_location);
}

">=" {
    TRACE("GE")
    ADVANCE();
    return yy::parser::make_GE(lexer_symbol_location);
}

">" {
    TRACE("GT")
    ADVANCE();
    return yy::parser::make_GT(lexer_symbol_location);
}

"{" {
    TRACE("LBRACE")
    ADVANCE();
    return yy::parser::make_LBRACE(lexer_symbol_location);
}

"!" {
    TRACE("LOGICAL_NOT")
    ADVANCE();
    return yy::parser::make_LOGICAL_NOT(lexer_symbol_location);
}

"(" {
    TRACE("LPAREN")
    ADVANCE();
    return yy::parser::make_LPAREN(lexer_symbol_location);
}

"<=" {
    TRACE("LE")
    ADVANCE();
    return yy::parser::make_LE(lexer_symbol_location);
}

"<" {
    TRACE("LT")
    ADVANCE();
    return yy::parser::make_LT(lexer_symbol_location);
}

"-" {
    TRACE("MINUS")
    ADVANCE();
    return yy::parser::make_MINUS(lexer_symbol_location);
}

"+" {
    TRACE("PLUS")
    ADVANCE();
    return yy::parser::make_PLUS(lexer_symbol_location);
}

"?" {
    TRACE("QUERY")
    ADVANCE();
    return yy::parser::make_QUERY(lexer_symbol_location);
}

"}" {
    TRACE("RBRACE")
    ADVANCE();
    return yy::parser::make_RBRACE(lexer_symbol_location);
}

")" {
    TRACE("RPAREN")
    ADVANCE();
    return yy::parser::make_RPAREN(lexer_symbol_location);
}

";" {
    TRACE("SEMICOLON")
    ADVANCE();
    return yy::parser::make_SEMICOLON(lexer_symbol_location);
}

"*" {
    TRACE("STAR")
    ADVANCE();
    return yy::parser::make_STAR(lexer_symbol_location);
}


[A-Za-z_.][A-Za-z0-9_.-]* {
    IdentifierToken tok{current_location, g_script.identifiers.toId(yytext)};
    ADVANCE();
    auto regularised = g_script.identifiers.toDisplayName(tok.id);
    TRACE("IDENTIFIER: " << yytext << " regularised to " << regularised)
    return yy::parser::make_IDENTIFIER(tok);
}

\"([^"\\\n]|\\.)*\" {
    std::size_t len = strlen(yytext);
    std::string unescaped;
    unescaped.reserve(len - 2);
    for (std::size_t i = 1; i < len - 1; ++i) {
        if (yytext[i] == '\\')
            ++i;
        unescaped.push_back(yytext[i]);
    }
    IdentifierToken tok{current_location, g_script.identifiers.toId(unescaped)};
    ADVANCE();
    auto regularised = g_script.identifiers.toDisplayName(tok.id);
    TRACE("IDENTIFIER: " << yytext << " regularised to " << regularised)
    return yy::parser::make_IDENTIFIER(tok);
}

0x[0-9A-Fa-f]+[KMkm]? {
    char* endptr;
    errno = 0;
    IntegerToken tok{current_location, strtoull(yytext, &endptr, 16)};
    if (tok.value == ULLONG_MAX && errno == ERANGE)
        throw DiagnosticError(current_location, "Integer overflow");
    if (endptr < yytext + yyleng)
        switch (*endptr) {
        case 'M':
        case 'm':
            if (tok.value > (UINT64_MAX >> 10))
                throw DiagnosticError(current_location, "Integer overflow");
            tok.value <<= 10;
            [[fallthrough]];
        case 'K':
        case 'k':
            if (tok.value > (UINT64_MAX >> 10))
                throw DiagnosticError(current_location, "Integer overflow");
            tok.value <<= 10;
        }
    ADVANCE();
    TRACE("INTEGER: " << yytext << " regularised to " << tok.value)
    return yy::parser::make_INTEGER(tok);
}

0[0-7]*[KMkm]? {
    char* endptr;
    errno = 0;
    IntegerToken tok{current_location, strtoull(yytext, &endptr, 8)};
    if (tok.value == ULLONG_MAX && errno == ERANGE)
        throw DiagnosticError(current_location, "Integer overflow");
    if (endptr < yytext + yyleng)
        switch (*endptr) {
        case 'M':
        case 'm':
            if (tok.value > (UINT64_MAX >> 10))
                throw DiagnosticError(current_location, "Integer overflow");
            tok.value <<= 10;
            [[fallthrough]];
        case 'K':
        case 'k':
            if (tok.value > (UINT64_MAX >> 10))
                throw DiagnosticError(current_location, "Integer overflow");
            tok.value <<= 10;
        }
    ADVANCE();
    TRACE("INTEGER: " << yytext << " regularised to " << tok.value)
    return yy::parser::make_INTEGER(tok);
}

[1-9][0-9]*[KMkm]? {
    char* endptr;
    errno = 0;
    IntegerToken tok{current_location, strtoull(yytext, &endptr, 10)};
    if (tok.value == ULLONG_MAX && errno == ERANGE)
        throw DiagnosticError(current_location, "Integer overflow");
    if (endptr < yytext + yyleng)
        switch (*endptr) {
        case 'M':
        case 'm':
            if (tok.value > (UINT64_MAX >> 10))
                throw DiagnosticError(current_location, "Integer overflow");
            tok.value <<= 10;
            [[fallthrough]];
        case 'K':
        case 'k':
            if (tok.value > (UINT64_MAX >> 10))
                throw DiagnosticError(current_location, "Integer overflow");
            tok.value <<= 10;
        }
    ADVANCE();
    TRACE("INTEGER: " << yytext << " regularised to " << tok.value)
    return yy::parser::make_INTEGER(tok);
}

\n {
    ADVANCE();
    g_source_manager.addLine(current_location);
}

<<EOF>> {
    g_source_manager.completeLineTable(current_location.file);
    if (!resume_locations.empty()) {
        yypop_buffer_state(); // auto-deletes the popped buffer
        current_location = resume_locations.back();
        resume_locations.pop_back();
        DiagnosticError::pop_include();
        /* no need for a return statement! */
    } else {
        auto old_buffer = YY_CURRENT_BUFFER;
        g_input_queue.pop();
        if (g_input_queue.empty()) {
            yy_delete_buffer(old_buffer);
            return yy::parser::make_YYEOF();
        }
        auto& input = *g_input_queue.front();
        current_location.file = input.getFileId();
        current_location.offset = 0;
        yy_switch_to_buffer(my_scan_buffer(input.getFileId()));
        yy_delete_buffer(old_buffer);
        /* no need for a return statement! */
    }
}

. {
    static char buf[80];
    if (yytext[0] < ' ' || yytext[0] >= 127)
        sprintf(buf, "error: unexpected byte 0x%02X", (uint8_t) yytext[0]);
    else
        sprintf(buf, "error: unexpected byte '%c'", yytext[0]);
    throw DiagnosticError(current_location, buf);
}

%%
/* Literal insertions into lexer.cpp (near bottom) */

/* This is an alternative to yy_scan_buffer(), because current versions of
 * flex generate that function such that it automatically calls
 * yy_switch_to_buffer() which swaps out whatever is at the top of the
 * buffer stack for the newly-created buffer. That is absolutely not what
 * want when doing inclusions! Note that yy_scan_bytes() and
 * yy_scan_string() both use yy_scan_buffer() as a back-end and so are not
 * suitable alternatives.
 */
static YY_BUFFER_STATE my_scan_buffer(FileId id)
{
    auto& lexer_buffer = g_source_manager.storage(g_source_manager.file(id).storage).lexer_buffer;
    // Use yy_create_buffer to create a template that we override as necessary.
    // Hopefully this will innoculate us a bit against structure changes in later versions of flex!
    auto buffer = yy_create_buffer(NULL, 0);
    yyfree((void*) buffer->yy_ch_buf); // we don't use the buffer allocated
    buffer->yy_ch_buf = buffer->yy_buf_pos = const_cast<char*>(lexer_buffer.data());
    buffer->yy_buf_size = buffer->yy_n_chars = lexer_buffer.size() - 2;
    buffer->yy_is_our_buffer = 0;
    buffer->yy_fill_buffer = 0;
    return buffer;
}

void lexer_set_initial_input(const TopLevelSource& input)
{
    current_location.file = input.getFileId();
    current_location.offset = 0;
    yy_switch_to_buffer(my_scan_buffer(input.getFileId()));
}

void lexer_push_include(FileId new_file)
{
    yypush_buffer_state(my_scan_buffer(new_file));
    resume_locations.push_back(current_location);
    current_location.file = new_file;
    current_location.offset = 0;
}
